version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_URI=mongodb://mongo:27017/order-management
      - JWT_SECRET=your_super_secret_jwt_key_change_this_in_production
      - JWT_ACCESS_EXPIRES_IN=15m
      - JWT_REFRESH_SECRET=your_super_secret_refresh_key_change_this_in_production
      - JWT_REFRESH_EXPIRES_IN=7d
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - KAFKA_BROKER=kafka:9092
      - PG_HOST=postgres
      - PG_PORT=5432
      - PG_USER=admin
      - PG_PASSWORD=secret
      - PG_DB=order_logs
    depends_on:
      - mongo
      - redis
      - kafka
      - postgres

  mongo:
    image: mongo:7.0
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: order_logs
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  mongo_data:
  redis_data:
  postgres_data:
